version: "3.8"

services:
  redis_db:
    image: redis
    ports:
      - "6379:6379"

  django: &django
    hostname: template-converter
    build:
      context: ../../
      dockerfile: "./init/local/django/Dockerfile"
    image: converter_local_django_qa
    depends_on:
      - redis_db
    volumes:
      - ../../:/app
    env_file: ../../.env
    ports:
      - "127.0.0.1:8001:8001"
    command: /start

networks:
  default:
    name: template-converter
