version: "3.8"

services:
  redis_db:
    image: redis
    ports:
      - "6379:6379"

  django: &django
    hostname: template-converter
    build:
      context: ../../
      dockerfile: ./Dockerfile
    depends_on:
      - redis_db
    image: converter_production_django_dev
    env_file: ../../.env
    ports:
      - "127.0.0.1:8888:8888"
    command: /start

networks:
  default:
    name: template-converter
